---
- hosts: all
  become: yes
 
  tasks:
  # apt-get install git
  - name: I want to install git on nodes
    apt:
     name: git
     state: present

  #apt-get install wget

  - name: I want install wget on nodes
    apt: 
     name: wget
     state: present